### ISSUE TITLE
Getting 'No such file or directory' error when trying to run Node.js in .Net core app

### ISSUE THREAD

**Issue by bperry77** [cloudfoundry/dotnet-core-buildpack#126]
I have a CF application that uses the [ASPNet/JavaScriptServices](https://github.com/aspnet/JavaScriptServices) project.  In my case, I have created an Angular2 application.  One of the features provided by this project is server-side prerendering.  To do this, a package called [NodeServices](https://github.com/aspnet/JavaScriptServices/tree/dev/src/Microsoft.AspNetCore.NodeServices) was created that allows invoking Node.js code from a .Net Core web application.

I am getting the following error:

`    System.ComponentModel.Win32Exception: No such file or directory
   at System.Diagnostics.Process.ResolvePath(String filename)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.LaunchNodeProcess(ProcessStartInfo startInfo)
   at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance..ctor(String entryPointScript, String projectPath, String[] watchFileExtensions, String commandLineArguments, ILogger nodeOutputLogger, IDictionary`2 environmentVars, Int32 invocationTimeoutMilliseconds, Boolean launchWithDebugging, Int32 debuggingPort)
   at Microsoft.AspNetCore.NodeServices.HostingModels.HttpNodeInstance..ctor(String projectPath, String[] watchFileExtensions, ILogger nodeInstanceOutputLogger, IDictionary`2 environmentVars, Int32 invocationTimeoutMilliseconds, Boolean launchWithDebugging, Int32 debuggingPort, Int32 port)
   at Microsoft.AspNetCore.NodeServices.NodeServicesFactory.CreateNodeInstance(NodeServicesOptions options)
   at Microsoft.AspNetCore.NodeServices.NodeServicesFactory.<>c__DisplayClass0_0.<CreateNodeServices>b__0()
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.CreateNewNodeInstance()
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.GetOrCreateCurrentNodeInstance()
   at Microsoft.AspNetCore.NodeServices.NodeServicesImpl.<InvokeExportWithPossibleRetryAsync>d__10`1.MoveNext()`

That made me think that this buildpack does not contain Node.js so I decided to investigate on this repo.  However, it looks like node binaries are included and I can confirm that my cf push used the 1.0.6 version.

Is it just that node is not available in the path variable and .NET cannot find it?  Any help would be greatly appreciated.

**Comment by degrim** [comment]
@bperry77 Currently, the node binaries are only installed in the container and added to the path if the project.json file indicates that a bower/npm command needs to be run in pre or post-compile scripts.  If your project.json file does not include one of these sections with a bower/npm command, node will not be installed.  To fix this, add something like:

```json
"scripts": {
  "precompile": [ "npm install" ]
}

to your project.json.
```

**Comment by bperry77** [comment]
@degrim Thanks!  That did install node but I did have an issue and the app would not start.  Found the following in the logs:

`npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue`

So I replaced the "npm install" with "npm update -g minimatch" which obviously addresses the warn and allowed my app to start.  Certainly a bit of a hack but it will do for now.

**Comment by degrim** [comment]
@sesmith177 @RochesterinNYC What do you think about adding an environment variable to install Node when npm/bower are not being used, but Node itself is required?

**Comment by bperry77** [comment]
@degrim I personally would like that since on the development side, I do not need VS to perform those pre  or post compile scripts.  I only need Node at runtime.

Thanks for your help!

**Comment by keaty** [comment]
Not sure if it would be an environment variable or something else, but allowing the user some way to specify they'd like to install Node seems useful. @sclevine, what is our plan going forward regarding configuration mechanisms?

**Comment by sclevine** [comment]
@degrim @bperry77 This seems reasonable to me. How about `INSTALL_NODE=true` or `FORCE_INSTALL_NODE=true`?

**Comment by degrim** [comment]
@sclevine `INSTALL_NODE=true` seems like a good choice to me.

**Comment by sclevine** [comment]
Story: https://www.pivotaltracker.com/story/show/137382231

**Comment by sesmith177** [comment]
This has been implemented on the `develop` branch: https://github.com/cloudfoundry/dotnet-core-buildpack/commit/ef878feb03d1db94701c0ec04164159c2fa0e730 and should be in the next release.
