### ISSUE TITLE
DEPENDENCY_MISSING_IN_MANIFEST: dotnet-framework.1.1.1.linux-amd64.tar.gz

### ISSUE THREAD

**Issue by gsainagendraprasad** [cloudfoundry/dotnet-core-buildpack#141]
I ran this command  **cf push -f manifest.yml** , I am trying to push a dotnet core service and i am getting BuildpackCompileFailed error . Here is my manifest yml file contents:
---
applications:
- name: fortuneService
  path: bin/Debug/netcoreapp1.1/publish
  env:
    ASPNETCORE_ENVIRONMENT: Development
  services:
   - myDiscoveryService

I am getting BuildpackCompileFailed

 Detected .NET Core runtime version 1.1.1 in /tmp/app/Fortune-Teller-Service.runtimeconfig.json
 Installing required .NET Core runtime(s)
 Downloading and installing .NET Core runtime 1.1.1
 DEPENDENCY_MISSING_IN_MANIFEST: dotnet-framework.1.1.1.linux-amd64.tar.gz
 FAILED: command failed, exit status 1
 FAILED: Installing required .NET Core runtime(s) failed, command failed, exit status 1

**Comment by sesmith177** [comment]
@gsainagendraprasad what version of the buildpack are you using?

**Comment by gsainagendraprasad** [comment]
@sesmith177,  Its ASP.NET Core buildpack version: 1.0.11. I haven't specified any build pack name in manifest file.

**Comment by degrim** [comment]
@gsainagendraprasad .NET Core runtime version 1.1.1 wasn't added until buildpack version 1.0.13.  If that version isn't installed in your environment you'll need to specify this GitHub repo as the buildpack when pushing your application in order to use that runtime version.

**Comment by gsainagendraprasad** [comment]
@degrim Hi Grim, I got it , i will try specifying the version and will let you either way. Thank you.

**Comment by gsainagendraprasad** [comment]
@degrim , Hi Grim,
Any idea how to specify the build pack version in manifest yml file,  I need to use .NET core runtime 1.1 and for that i need to use buildpack 1.0.13 as you specified. But in manifest if i just specify the build pack name it is still taking buildpack 1.0.11 , so i may have to specify the build pack version explicitly but i am not sure how to specify it.
here is my manifest file:
---
applications:
- name: fortuneService
  path: bin/Debug/netcoreapp1.1/publish
  buildpack: dotnet-core_buildpack
  env:
    ASPNETCORE_ENVIRONMENT: Development
  services:
   - myDiscoveryService

**Comment by degrim** [comment]
@gsainagendraprasad Change the `buildpack` field from `dotnet-core_buildpack` to `https://github.com/cloudfoundry/dotnet-core-buildpack.git`

**Comment by gsainagendraprasad** [comment]
@degrim , Hi Grim,  I just tried this and i am getting error in staging saying Failed to clone git repository at https://github.com/cloudfoundry/dotnet-core-buildpack.git

**Comment by gsainagendraprasad** [comment]
It could be my environment issue with power shell,  When i tried this to clone this repository using cmd prompt it was able to clone it. Where as in both power shell  and cmd prompt  it is not able to clone as part of cf push command :(

**Comment by sclevine** [comment]
The buildpack clone during `cf push` happens in the application container, not locally. That error suggests that your application containers don't have internet access during staging.

If this is the case, you'll need to upload an offline version of the buildpack (ex. https://github.com/cloudfoundry/dotnet-core-buildpack/releases/download/v1.0.16/dotnet-core_buildpack-cached-v1.0.16.zip) to your foundation using `cf create-buildpack`.

**Comment by gsainagendraprasad** [comment]
@sclevine  - Which means  I am back to step 1 : I have to run this two commands, destroy the cf dev,
 >> $env:HTTP_PROXY = "http://PROXY_IP:PROXY_PORT"
>> $env:HTTPS_PROXY = "http://PROXY_IP:PROXY_PORT"
then  i should say : **cf dev start -s scs**

Is there any other solution? I am getting this issue quite often :(

**Comment by sclevine** [comment]
That should work -- you'll want to set `NO_PROXY` to allow the cf CLI to work though. See: https://docs.pivotal.io/pcf-dev/proxy.html

**Comment by gsainagendraprasad** [comment]
It is not working either way, i tried to upload a offline version of the build pack using this cf create-buildpack command  , when i run this command my power shell window becomes ideal and it does nothing.
I also tried to destroy the CF and started it back using the proxy settings then also i am not able to clone the get repository (which means my container is not have internet access). 

Now the only option left for me is to write a dotnet core service which uses .NET core runtime 1.0 and push it using dotnetbuildpack V 1.0.11.  Not sure if this is going to work :(

**Comment by gsainagendraprasad** [comment]
@sclevine . Hi Here is what i got when i tried to create a build pack , 

Failed to create a local temporary zip file for the buildpack
FAILED
Couldn't write zip file: Get https://github.com/cloudfoundry/dotnet-core-buildpack/releases/download/v1.0.16/dotnet-core
_buildpack-cached-v1.0.16.zip: read tcp 172.22.60.32:65193->192.30.253.113:443: wsarecv: An existing connection was forcibly closed by the remote host.

**Comment by sclevine** [comment]
You need to download it first.

**Comment by gsainagendraprasad** [comment]
@sclevine  I am able to create this offline build pack now. I also written my own client(UI) application which uses discovery client and will fetch data from registered service. When i try to push this client in to pcf dev, staging process is done went into cell and application crashed with this error.

2017-04-28T15:56:24.73-0500 [CELL/0] OUT Starting health monitoring of container
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR Unhandled Exception: System.IO.FileLoadException: **Could not load file o
r assembly 'Microsoft.Extensions.Configuration.EnvironmentVariables, Version=1.1.0.0, Culture=neutral, PublicKeyToken=ad
b9793829ddae60'. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESU
LT: 0x80131040)**
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR    at Steeltoe.Extensions.Configuration.CloudFoundry.CloudFoundryConfig
urationProvider.Load()
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.Configuration.ConfigurationRoot..ctor(IList`
1 providers)
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.Configuration.ConfigurationBuilder.Build()
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR    at Client.Startup..ctor(IHostingEnvironment env)
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR --- End of stack trace from previous location where exception was throw
n ---
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.Internal.ActivatorUtilities.ConstructorMatch
er.CreateInstance(IServiceProvider provider)
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR    at Microsoft.AspNetCore.Hosting.Internal.StartupLoader.LoadMethods(I
ServiceProvider services, Type startupType, String environmentName)
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR    at Microsoft.AspNetCore.Hosting.WebHostBuilderExtensions.<>c__Displa
yClass1_0.<UseStartup>b__1(IServiceProvider sp)
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceProvider.ScopedCa
llSite.Invoke(ServiceProvider provider)
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceEx
tensions.GetRequiredService(IServiceProvider provider, Type serviceType)
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR    at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceEx
tensions.GetRequiredService[T](IServiceProvider provider)
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureStartup()
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR    at Microsoft.AspNetCore.Hosting.Internal.WebHost.EnsureApplicationSe
rvices()
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR    at Microsoft.AspNetCore.Hosting.Internal.WebHost.BuildApplication()
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR    at Microsoft.AspNetCore.Hosting.WebHostBuilder.Build()
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR    at Client.Program.Main(String[] args)
2017-04-28T15:56:25.12-0500 [APP/PROC/WEB/0] ERR bash: line 1:    20 Aborted                 dotnet Client.dll --server.
urls http://0.0.0.0:${PORT}

**Comment by gsainagendraprasad** [comment]
@sclevine  , I downloaded it and then did a create-buildpack and it worked . I am able to push it pcf dev. Thanks Stephen.

**Comment by sclevine** [comment]
Glad to hear that you got it working!
