### ISSUE TITLE
What Cloud Foundry versions are supported by this buildpack?

### ISSUE THREAD

**Issue by mgoovaer** [cloudfoundry/dotnet-core-buildpack#145]
We're encountering issues deploying on 1.6
Thanks!

**Comment by sclevine** [comment]
We CI the buildpack back as far as CF 225. What issue are you running into on (PCF?) 1.6?

**Comment by mgoovaer** [comment]
@sclevine yup on PCF 1.6, when deploying a .netcore application it's failing to compile the buildpack.

Here are the logs:
```
Starting app {app-name} in org {org-name} / space {space-name} as mgoovaer...
Creating container
Successfully created container
Downloading app package...
Downloaded app package (6.7M)
Staging...
-----> Buildpack version 1.0.18
ASP.NET Core buildpack version: 1.0.18
ASP.NET Core buildpack starting compile
-----> Restoring files from buildpack cache
       OK
-----> Restoring NuGet packages cache
       OK
-----> Extracting libunwind
       libunwind version: 1.2
       /usr/lib/ruby/2.2.0/digest.rb:49:in `initialize': No such file or directory @ rb_sysopen - /tmp/libunwind-x-1.2.tar.gz (Errno::ENOENT)
       	from /usr/lib/ruby/2.2.0/digest.rb:49:in `open'
       	from /usr/lib/ruby/2.2.0/digest.rb:49:in `file'
       	from /usr/lib/ruby/2.2.0/digest.rb:34:in `file'
       	from /tmp/buildpacks/c405f3cc2cbad82abd8c07e23d682835/compile-extensions/bin/download_dependency:20:in `<main>'
       FAILED: command failed, exit status 1
       FAILED: Extracting libunwind failed, command failed, exit status 1
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223

FAILED
Error restarting application: BuildpackCompileFailed
```

**Comment by sclevine** [comment]
Can you provide a sample app that demonstrates this failure?

**Comment by mgoovaer** [comment]
@sclevine we can actually close this out, it was caused by our environment not being setup with a valid certificate so it was unable to fetch some dependencies.
