### ISSUE TITLE
node_modules/.bin not on PATH of app with project.json

### ISSUE THREAD

**Issue by opiethehokie** [cloudfoundry/dotnet-core-buildpack#165]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

CF v253 and cf version 6.26.0+9c9a261fd.2017-04-06

What version of the buildpack you are using?

v1.0.26

If you were attempting to accomplish a task, what was it you were attempting to do?

Run `gulp min` as a precompile projet.json command

To reproduce:
- download [portable-npm.zip](https://github.com/cloudfoundry/dotnet-core-buildpack/files/1307166/portable-npm.zip)
- `cf push myapp -p portable-npm.zip`

What did you expect to happen?

gulp to be on the PATH because it was with the v1.0.22 buildpack, app starts successfully

What was the actual behavior?

gulp is installed, but not on the PATH. The app won't start because of of the following error:
```
2017-09-15T13:07:06.18-0400 [CELL/0] OUT Starting health monitoring of container
2017-09-15T13:07:06.93-0400 [APP/PROC/WEB/0] OUT Project dotnetstarter (.NETCoreApp,Version=v1.0) will be compiled because project is not safe for incremental compilation. Use --build-profile flag for more information.
2017-09-15T13:07:06.97-0400 [APP/PROC/WEB/0] OUT Compiling dotnetstarter for .NETCoreApp,Version=v1.0
...
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] ERR Microsoft.DotNet.Cli.Utils.CommandUnknownException: No executable found matching command "gulp"
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] ERR    at Microsoft.DotNet.Cli.Utils.Command.CreateForScript(String commandName, IEnumerable`1 args, Project project, String[] inferredExtensionList)
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] ERR    at Microsoft.DotNet.Cli.Utils.ScriptExecutor.CreateCommandForScript(Project project, String scriptCommandLine, Func`2 getVariable)
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] ERR    at Microsoft.DotNet.Cli.Utils.ScriptExecutor.CreateCommandForScript(Project project, String scriptCommandLine, IDictionary`2 variables)
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] ERR    at Microsoft.DotNet.Tools.Compiler.ScriptRunner.RunScripts(ProjectContext context, String name, Dictionary`2 contextVariables)
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] ERR    at Microsoft.DotNet.Tools.Build.DotNetProjectBuilder.RunCompile(ProjectGraphNode projectNode)
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] ERR    at Microsoft.DotNet.Tools.Build.ProjectBuilder.CompileWithDependencies(ProjectGraphNode projectNode)
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] ERR    at Microsoft.DotNet.Tools.Compiler.ManagedCompiler.Compile(ProjectContext context, BuildCommandApp args)
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] ERR    at Microsoft.DotNet.Tools.Build.ProjectBuilder.Build(ProjectGraphNode projectNode)
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] ERR    at Microsoft.DotNet.Tools.Build.BuildCommand.OnExecute(IEnumerable`1 files, IEnumerable`1 frameworks, BuildCommandApp args)
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] ERR    at Microsoft.DotNet.Cli.CommandLine.CommandLineApplication.Execute(String[] args)
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] ERR    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source, Int32& length)
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] ERR    at Microsoft.DotNet.Tools.Compiler.BuildCommandApp.<>c__DisplayClass57_0.<Execute>b__0()
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] ERR    at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] ERR    at Microsoft.DotNet.Tools.Build.DotNetProjectBuilder.Build(ProjectGraphNode projectNode)
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] ERR    at Microsoft.DotNet.Tools.Compiler.BuildCommandApp.Execute(OnExecute execute, String[] args)
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] ERR    at Microsoft.DotNet.Tools.Build.ProjectBuilder.<Build>d__3.MoveNext()
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] ERR    at Microsoft.DotNet.Tools.Build.BuildCommand.Run(String[] args, BuildWorkspace workspace)
2017-09-15T13:07:30.82-0400 [APP/PROC/WEB/0] OUT Exit status 1
2017-09-15T13:07:30.84-0400 [CELL/0] OUT Exit status 0
```

Please confirm where necessary:
* [X] I have included a log output
* [X] My log includes an error message
* [X] I have included steps for reproduction

**Comment by opiethehokie** [comment]
As a workaround you can use a .profile file like https://github.com/cloudfoundry/dotnet-core-buildpack/blob/master/cf_spec/fixtures/angular/.profile. Should that be necessary?

**Comment by sclevine** [comment]
Hi @opiethehokie,

Thanks for the report. This is prioritized for next iteration.
