### ISSUE TITLE
Unable to determine .NET Core runtime version(s) to install (RuntimeError)

### ISSUE THREAD

**Issue by JayVictor** [cloudfoundry/dotnet-core-buildpack#166]
What version of the buildpack you are using?
dotnet_core_buildpack

If you were attempting to accomplish a task, what was it you were attempting to do?
I was pushing the app through TFS. (My Build and Release went successful). . But the app is not starting automatically even though “Start on Deploy” box is checked. So, I tried to start the app manually and we are getting below errors

-----> Installing .NET SDK
.NET SDK version: 1.0.4
file:///tmp/buildpacks/918fb3b9b2b0c639f5075dde905f1af0/dependencies/https___buildpacks.cloudfoundry.org_dependencies_dotnet_dotnet.1.0.4.linux-amd64-51ccea2c.tar.gz
OK
-----> Restoring dependencies with Dotnet CLI
OK
from /tmp/buildpacks/918fb3b9b2b0c639f5075dde905f1af0/lib/buildpack/compile/compiler.rb:88:in `should_install_framework?'
from /tmp/buildpacks/918fb3b9b2b0c639f5075dde905f1af0/lib/buildpack/compile/dotnet_framework.rb:51:in `should_install?'
from /tmp/buildpacks/918fb3b9b2b0c639f5075dde905f1af0/lib/buildpack/compile/compiler.rb:69:in `compile'
from /tmp/buildpacks/918fb3b9b2b0c639f5075dde905f1af0/lib/buildpack.rb:30:in `compile'
from /tmp/buildpacks/918fb3b9b2b0c639f5075dde905f1af0/lib/buildpack/compile/dotnet_framework.rb:71:in `versions'
from /tmp/buildpacks/918fb3b9b2b0c639f5075dde905f1af0/bin/compile.rb:55:in `<main>'
/tmp/buildpacks/918fb3b9b2b0c639f5075dde905f1af0/lib/buildpack/compile/dotnet_framework_version.rb:45:in `versions': Unable to determine .NET Core runtime version(s) to install (RuntimeError)
Failed to compile droplet
Exit status 223
Staging failed: Exited with status 223

What did you expect to happen?
My app should load

**Comment by JayVictor** [comment]
Could you please let me know on how to resolve the issue?
