### ISSUE TITLE
Machete test fails for app asp_prerender_node

### ISSUE THREAD

**Issue by arghya88** [cloudfoundry/dotnet-core-buildpack#170]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

CF api_version": "2.65.0"
CF CLI version : cf version 6.23.1+a70deb3.2017-01-13
What version of the buildpack you are using?

buildpack-1.0.27

If you were attempting to accomplish a task, what was it you were attempting to do?

Trying to run integration test suite using machete

What did you expect to happen?

Expected to pass all the tests

What was the actual behavior?

One test failed with below error:

1) CF ASP.NET Core Buildpack deploying an mvc app with node prerendering displays a page rendered by node
     Failure/Error: browser.visit_path('/')
     
     Machete::HTTPServerError:
     responded with error code 500
     ./cf_spec/integration/deploy_dotnetcore_app_spec.rb:53:in `block (3 levels) in <top (required)>'
    displays a page rendered by node (FAILED - 1)

I also tried cf push for asp_prerender_node and then hitting the route in browser returns 500 error
Tried pushing the app after performing dotnet publish and got same error

There is no error while staging the app. When I hit the URL in browser I am seeing below error in app logs:

2017-10-11T16:30:47.64+0530 [APP/PROC/WEB/0]OUT dbug: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
2017-10-11T16:30:47.64+0530 [APP/PROC/WEB/0]OUT       Executing action HelloMvc.HomeController.AddNumbers (asp_prerender_node)
2017-10-11T16:30:47.77+0530 [APP/PROC/WEB/0]OUT info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[1]
2017-10-11T16:30:47.77+0530 [APP/PROC/WEB/0]OUT       Executing action method HelloMvc.HomeController.AddNumbers (asp_prerender_node) with arguments (Microsoft.AspNetCore.NodeServices.NodeServicesImpl) - ModelState is Valid
2017-10-11T16:30:47.81+0530 [APP/PROC/WEB/0]OUT info: Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker[2]
2017-10-11T16:30:47.81+0530 [APP/PROC/WEB/0]OUT       Executed action HelloMvc.HomeController.AddNumbers (asp_prerender_node) in 162.194ms
2017-10-11T16:30:47.84+0530 [APP/PROC/WEB/0]OUT fail: Microsoft.AspNetCore.Server.Kestrel[13]
2017-10-11T16:30:47.84+0530 [APP/PROC/WEB/0]OUT       Connection id "0HL8GIT3ET7FA": An unhandled exception was thrown by the application.
2017-10-11T16:30:47.84+0530 [APP/PROC/WEB/0]OUT System.InvalidOperationException: Failed to start Node process. To resolve this:.
2017-10-11T16:30:47.84+0530 [APP/PROC/WEB/0]OUT [1] Ensure that Node.js is installed and can be found in one of the PATH directories.
2017-10-11T16:30:47.84+0530 [APP/PROC/WEB/0]OUT     Current PATH enviroment variable is: /home/vcap/app/.cloudfoundry/0/bin:/usr/local/bin:/usr/bin:/bin
2017-10-11T16:30:47.84+0530 [APP/PROC/WEB/0]OUT     Make sure the Node executable is in one of those directories, or update your PATH.
2017-10-11T16:30:47.84+0530 [APP/PROC/WEB/0]OUT [2] See the InnerException for further details of the cause. ---> System.ComponentModel.Win32Exception: No such file or directory
2017-10-11T16:30:47.84+0530 [APP/PROC/WEB/0]OUT    at System.Diagnostics.Process.ResolvePath(String filename)
2017-10-11T16:30:47.84+0530 [APP/PROC/WEB/0]OUT    at Microsoft.AspNetCore.NodeServices.HostingModels.OutOfProcessNodeInstance.LaunchNodeProcess(ProcessStartInfo startInfo)
2017-10-11T16:30:47.84+0530 [APP/PROC/WEB/0]OUT    --- End of inner exception stack trace ---

Please confirm where necessary:
* [ ] I have included a log output
* [ ] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by sclevine** [comment]
Hi @arghya88,

Can you see if these tests pass from inside the cloudfoundry/cflinuxfs2 Docker image?

**Comment by sclevine** [comment]
Closing this due to inactivity. Let us know if you're still having trouble getting the tests to pass with the latest version of the buildpack.
