### ISSUE TITLE
Problem starting app with cached Buildpack

### ISSUE THREAD

**Issue by chlamprecht** [cloudfoundry/dotnet-core-buildpack#173]
What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

CF Version 1.10

What version of the buildpack you are using?

1.0.31. Build from source as chached buildpack.

If you were attempting to accomplish a task, what was it you were attempting to do?

Starting the app :)

What was the actual behavior?

```
2017-11-22T16:47:04.606+01:00 [STG/0] [OUT] Staging...
2017-11-22T16:47:04.825+01:00 [STG/0] [OUT] -----> Buildpack version 1.0.31
2017-11-22T16:47:04.825+01:00 [STG/0] [ERR] from /usr/lib/ruby/2.3.0/open3.rb:199:in `popen_run'
2017-11-22T16:47:04.825+01:00 [STG/0] [ERR] /usr/lib/ruby/2.3.0/open3.rb:199:in `spawn': No such file or directory - /tmp/buildpacks/3aad05ba60a9a40988c4d63fe6fa98b9/bin/../compile-extensions/bin/build_path_from_supply (Errno::ENOENT)
2017-11-22T16:47:04.825+01:00 [STG/0] [ERR] from /usr/lib/ruby/2.3.0/open3.rb:258:in `capture3'
2017-11-22T16:47:04.825+01:00 [STG/0] [ERR] from /tmp/buildpacks/3aad05ba60a9a40988c4d63fe6fa98b9/bin/supply.rb:37:in `<main>'
2017-11-22T16:47:04.825+01:00 [STG/0] [ERR] from /usr/lib/ruby/2.3.0/open3.rb:95:in `popen3'
2017-11-22T16:47:04.831+01:00 [STG/0] [ERR] Failed to compile droplet
```

Please confirm where necessary:
* [x ] I have included a log output
* [x] My log includes an error message
* [ ] I have included steps for reproduction

appsettings.json:

`{  "Logging": {    "IncludeScopes": false,    "LogLevel": {      "Default": "Debug",      "System": "Information",      "Microsoft": "Information"    }  }}`

projct.json
`{  "dependencies": {    "Microsoft.NETCore.App": {      "version": "1.0.1",      "type": "platform"    },    "Microsoft.AspNetCore.Mvc": "1.0.1",    "Microsoft.AspNetCore.Routing": "1.0.1",    //"Microsoft.AspNetCore.Server.IISIntegration": "1.0.0",    "Microsoft.AspNetCore.Server.Kestrel": "1.0.1",    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0",    "Microsoft.Extensions.Configuration.FileExtensions": "1.0.0",    "Microsoft.Extensions.Configuration.Json": "1.0.0",    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0",    "Microsoft.Extensions.Configuration.CommandLine": "1.0.0"  },  "tools": {    //"Microsoft.AspNetCore.Server.IISIntegration.Tools": "1.0.1"  },  "frameworks": {    "netcoreapp1.0": {      "imports": [      ]    }  },  "buildOptions": {    "emitEntryPoint": true,    "preserveCompilationContext": true  },  "runtimeOptions": {    "configProperties": {      "System.GC.Server": true    }  },  "publishOptions": {    "include": [      "wwwroot",      "**/*.cshtml",      "appsettings.json",      "web.config"    ]  },  "scripts": {  }}`

Do you have any idea what the issuse could be?

With the 1.0.13 buildpack the apps seems working.

**Comment by sclevine** [comment]
Did you package this cached buildpack yourself?

If so, it appears that you did not check out the `compile-extensions` submodule before packaging it.

**Comment by chlamprecht** [comment]
Thanks that fixed the issue. A hint at the readme would be nice, if building an cached buildpack.
