### ISSUE TITLE
gdiplus required library not detected (and LD_LIBRARY_PATH feature not working?)

### ISSUE THREAD

**Issue by lameventanas** [cloudfoundry/dotnet-core-buildpack#241]
I'm trying to deploy a dotnet core application that uses the Aspose library, which in turn requires gdiplus.  If I push the app, the buildpack doesn't detect the need of gdiplus.  If I create an LD_LIBRARY_PATH and put the library (libgdiplus.so) there, I get the same error message.
The only way I can make it work is if I copy the library to the dotnet_publish directory as part of the startup command.

What version of Cloud Foundry and CF CLI are you using? (i.e. What is the output of running `cf curl /v2/info && cf version`?

```cf curl /v2/info && cf version
{
   "description": "Unknown request",
   "error_code": "CF-NotFound",
   "code": 10000
}
cf.exe version 6.51.0+2acd15650.2020-04-07
```
I'm using cloudfoundry/cf-deployment@271c02452390167e061bed86707f83ba3251d2bd

What version of the buildpack you are using?
2.3.9

If you were attempting to accomplish a task, what was it you were attempting to do?
Deploy an app that uses the Aspose library, which requires the gdiplus library.

Is your dotnet app unpublished, platform-dependant, or self-contained?
Not sure.

What did you expect to happen?
Everything working well, getting a promotion, buying a big house in Malibu.

What was the actual behavior?
I get this error message:
```
System.TypeInitializationException: The type initializer for 'Gdip' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libgdiplus': The specified module could not be found.
   at System.Runtime.InteropServices.FunctionWrapper`1.get_Delegate()
   at System.Drawing.SafeNativeMethods.Gdip.GdiplusStartup(IntPtr& token, StartupInput& input, StartupOutput& output)
   at System.Drawing.SafeNativeMethods.Gdip..cctor()
   --- End of inner exception stack trace ---
   at System.Drawing.SafeNativeMethods.Gdip.GdipLoadImageFromDelegate_linux(StreamGetHeaderDelegate getHeader, StreamGetBytesDelegate getBytes, StreamPutBytesDelegate putBytes, StreamSeekDelegate doSeek, StreamCloseDelegate close, StreamSizeDelegate size, IntPtr& image)
   at System.Drawing.Image.InitFromStream(Stream stream)
   at Aspose.BarCode.BarCodeRecognition.BarCodeReader.SetBarCodeImage(Stream stream)
   at Aspose.BarCode.BarCodeRecognition.BarCodeReader..ctor(Stream stream, BaseDecodeType type)
   at Barcode.Controllers.BarCodeController.Read(BarcodeRecognitionParameters barcodeRecognitionParameters) in /tmp/app/Controllers/BarCodeController.cs:line 152
```

Please confirm where necessary:
* [x] I have included a log output
* [x] My log includes an error message
* [ ] I have included steps for reproduction

**Comment by dwillist** [comment]
@lameventanas this buildpack is currently being re-written as part of the `paketo-buildpacks` project. I would recommend pushing this application as a `self-contained` or `platform dependent` application as the `libgdi` detection for these types of applications is more robust.
